### ISSUE TITLE
fp16 is not work

### ISSUE THREAD

**Issue by zsk423200** [huggingface/pytorch-transformers#871] opened 2019-07-23 11:52 UTC
GPU:v100

run run_glue.py with the command in the README:
```
python ./examples/run_glue.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --task_name $TASK_NAME \
    --do_train \
    --do_eval \
    --do_lower_case \
    --data_dir $GLUE_DIR/$TASK_NAME \
    --max_seq_length 128 \
    --per_gpu_eval_batch_size=8   \
    --per_gpu_train_batch_size=8   \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --output_dir /tmp/$TASK_NAME/
```
and i also run with --fp16,  but spend the same time and gpu memory, why fp16 does not work

**Comment by thomwolf** [comment] 2019-07-23 15:59
Duplicate of #868

**Closed by thomwolf** 2019-07-23 15:59 UTC
